[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "rimeX"
authors = [
    {name = "Mahé Perrette", email = "mahe.perrette@gmail.com"},
    {name = "Niklas Schwind", email = "schwind@iiasa.ac.at"},
    {name = "Edward byers", email = "byers@iiasa.ac.at"},
    {name = "Mia Werning", email = "werning@iiasa.ac.at"},
]

version = "1.0.0"
description='Combining simple climate models, Earth system models, and climate impact models into a unified statistical emulator for regional climate indicators'
readme = "README.md"
requires-python = ">=3.7"
keywords = ['climate', 'impact model', 'emulator', 'ISIMIP', 'global mean temperature']
license = "AGPL-3.0-or-later"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
  "toml",
  "numpy",
  "pandas",
  "xarray",
  "netcdf4",
  "h5netcdf",
  "tqdm",
  "flatdict",
  "isimip_client",
  "scipy",
]

[project.optional-dependencies]
all = [
    "isimip_client@https://github.com/ISI-MIP/isimip-client/archive/refs/tags/1.0.1.zip",
    "pyam-iamc",
    # below for rimeX legacy code and postprocessing to work as expected
    "dask[distributed]",
    "holoviews",
    "hvplot",
    # rimeX.legacy : plot dashboard:
    "cartopy",
    "geoviews",
    "pyproj",
    # rimeX.postproc.lifetime_exposure:
    "openpyxl",
    # tutorial notebooks:
    "jupyter",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["rimeX", "rimeX.legacy", "rimeX.preproc", "rimeX.postproc", "rimeX.datasets", "rimeX.scripts", "rimeX_datasets"]

[tool.setuptools.package-data]
rimeX = ["config.toml"]
"rimeX.legacy" = ["indicator_params.yml"]

[project.scripts]
rime-config = "rimeX.config:main"
rime-download-isimip = "rimeX.datasets.download_isimip:main"
rime-download = "rimeX.datasets.__main__:main"
rime-fit-distribution = "rimeX.preproc.distribution_fit:main"
rime-pre-gmt = "rimeX.preproc.global_average_tas:main"
rime-pre-region = "rimeX.preproc.regional_average:main"
rime-pre-wl = "rimeX.preproc.warminglevels:main"
rime-pre-digitize = "rimeX.preproc.digitize:main"
rime-pre-quantilemap = "rimeX.preproc.quantilemaps:main"
rime-run-timeseries = "rimeX.scripts.timeseries:main"
rime-run-map = "rimeX.scripts.map:main"
rime-run-table = "rimeX.scripts.table:main"

[project.urls]
homepage = "https://github.com/iiasa/rime/tree/rimeX"
